language: objective-c
osx_image: xcode7

env:
  global:
    - LANG=en_US.UTF-8

before_install:
  - gem install xcpretty-travis-formatter

# xctool is more trouble than it's worth...
# First no Xcode 7 support, then it suddenly hates the names of our tests? Forget it.
script:
  - xcodebuild -workspace Sidecar.xcworkspace -scheme Sidecar -configuration Debug -sdk iphonesimulator build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash)
